locales:
  - 'en_GB'
  - 'en_US'
  - 'fr_FR'
  - 'en_CA'
  - 'de_DE'
  - 'en_AU'
  - 'es_ES'
  - 'fr_BE'
  - 'it_IT'
  - 'ja_JP'
  - 'nl_NL'
  - 'pt_PT'

create_products:
  preorder_weeks: 6
  label_prefix:
    - 'LCR'
    - 'SUMO'
    - 'STDR'
    - 'KALA'
    - 'GAS'
    - 'PIL'
  pricing:
    - 18.0
    - 19.0
    - 20.0
    - 21.0
    - 22.0
