steps:
- name: "gcr.io/cloud-builders/docker"
  args:
  - build
  - "--tag=gcr.io/$PROJECT_ID/ecommerce-data-generator-api:v1"
  - "--file=./api/Dockerfile"
  - .
images:
- "gcr.io/$PROJECT_ID/ecommerce-data-generator-api:v1"