steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - build
      - "--tag=europe-west2-docker.pkg.dev/$PROJECT_ID/ecommerce/data-generator:$SHORT_SHA"
      - "--file=./ecommerce_data_generator/Dockerfile"
      - .
    id: "build"
  - name: "gcr.io/cloud-builders/docker"
    args:
      - push
      - "europe-west2-docker.pkg.dev/$PROJECT_ID/ecommerce/data-generator:$SHORT_SHA"
    id: "push"
images:
  - "europe-west2-docker.pkg.dev/$PROJECT_ID/ecommerce/data-generator:$SHORT_SHA"